## La clase Array
En esta lección vamos a aprender lo más básico sobre los *arrays*.

Los datos suelen presentarse en registros en forma de tablas, ya sea a través de ficheros o bases de datos, y los *arrays* nos ofrecen la forma perfecta de recuperarlos y trabajarlos.

### Creación

Numpy incluye una clase **array** (arreglo en español) con un montón de funcionalidades, así que vamos a hacer uso de ella para empezar nuestra andadura en el mundo del análisis de datos.

In [5]:
# Normalmente se suele importar numpy como np ya que nos ahorra tiempo
import numpy as np

La forma más sencilla de crear un *array* es hacerlo a partir de una lista, y es que en esencia ambas estructuras son muy parecidas:

In [6]:
list_1 = [1,2,3,4,5]

# Creamos un arreglo y lo mostramos
arr_1 = np.array(list_1)

arr_1

array([1, 2, 3, 4, 5])

Como podemos observar el tipo de la variable es array, ¿bastante obvio no? 

Por cierto, los arrays de una dimension se conocen también como **vectores**, y los arrays de dos dimensiones como **matrices**.

Vamos a ver cómo crear un array 2D a partir de una lista de listas (o lista anidada).

In [7]:
list_2 = [6,7,8,9,10]

# Lista de listas anidadas
nested_list = [list_1, list_2]

# Creamos un arreglo multidimensional y la mostramos
arr_2 = np.array(nested_list)

arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Evidentemente este proceso puede simplificarse en una sola línea:

In [8]:
arr_2 = np.array([list_1, list_2])

arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Tamaño
Para saber el tamaño de un array podemos utilizar su método de clase **shape**:

In [9]:
arr_2.shape

(2, 5)

La truducción de **shape** vendría a ser **forma** y nos indica el tamaño de cada dimensión del array. 

Así que la forma de éste es 2 x 5 (2 de largo por 5 de alto), es decir, una tabla con 2 filas de 5 columnas:

| 1 | 2 | 3 | 4 | &nbsp;5 |
|---|---|---|---|---|
| **6** | **7** | **8** | **9** | **10**|


### Tipo
El tipo de un array hace referencia al conjunto de datos que almacenan. Podemos consultar su tipo a través de su propiedad **dtype**:

In [10]:
arr_1.dtype

En este caso al almacenar números enteros pequeños, Numpy ha considerado que el tipo del arreglo fuera de enteros de 32 bits de manera que se optimiza la memoria. Lo propio ocurriría si almacenamos decimales u otro tipo:

In [7]:
arr_3 = np.array([3.1, 2.7, 5.5])
arr_3.dtype

dtype('float64')

Pero... ¿Y si el array no fuera homogéneo y tuviera datos de diferentes tipos?

In [8]:
arr_4 = np.array(["Hola", 3, 5.5])
arr_4.dtype

dtype('<U4')

¡Qué tipo de dato tan extraño! Si consultamos la [documentación oficial de Numpy](https://docs.scipy.org/doc/numpy-1.9.3/reference/arrays.dtypes.html) nos indica que U4 es Unicode, es decir, se transforma en un array de texto. De hecho si lo consultamos veremos como los valores ahora son cadenas entre comillas:

In [9]:
arr_4

array(['Hola', '3', '5.5'], 
      dtype='<U4')

Así que no olvidéis que dependiendo de los valores que guardemos en el array su tipo puede ser alterado.

## Ejercicios