## Arrays pre-generados
Crear arrays siempre a partir de listas puede ser muy tedioso, así que Numpy integra varias funciones muy útiles para generar arrays de uso común en el álgebra de matrices.   

### Array de ceros
Un array de ceros es cuando todos sus elementos son ceros. Podemos generarlos con el método **zeros** de Numpy:

In [7]:
import numpy as np

np.zeros(3)

array([ 0.,  0.,  0.])

Evidentemente podemos generar arrays multidimensionales, pero para ello tenemos que pasarle al método una lista o tupla con la longitud de sus dimensiones:

In [8]:
np.zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### Array de unos
Lo mismo podemos hacer pero utilizando el método **ones**:

In [9]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Array de identidad
Los arrays de identidad son matrices cuadradas (con el mismo número de filas que de columnas) donde todos los valores son ceros a excepción de la diagonal donde son unos. Podemos generarlos con el método **eye**:

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

*Las matrices de identidad son muy interesantes desde el punto de vista de la programación, ya que sus elementos son siempre cero menos cuando los índices de la fila y la columna son el mismo.*

### Array de rangos
Por último pero no por ello menos importante, también es posible generar arrays a partir de un rango de valores. 

Para hacerlo utilizaríamos el método **arange**:

In [18]:
# Rango de 0 a 4
np.arange(4)

array([0, 1, 2, 3])

In [26]:
# Rango 0 a 4 decimal
np.arange(4.)

array([ 0.,  1.,  2.,  3.])

In [28]:
# Rango de -3 a 4
np.arange(-3, 3)

array([-3, -2, -1,  0,  1,  2])

In [36]:
# Rango de 0 a 20 cada 5 números
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

## Ejercicios