## Índices y slicing en 1 dimensión
En la programación cuando trabajamos con colecciones de datos uno de los conceptos más importante es el **índice**.

El índice en los arrays funciona exactamente igual que en las listas, **es simplemente un número que hace referencia a la posición del array que queremos consultar o modificar**.

In [27]:
import numpy as np

arr = np.arange(0, 50, 5)

arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### Índices

La caracterítica más importante de los índices es que **se empiezan a contar desde cero**, no desde uno, por tanto para acceder al elemento de la primera posición del array utilizaremos el 0:

In [28]:
arr[0]

0

Si queremos saber el de la quinta posición, simplemente tomamos el 5 y le restamos 1, por tanto sería índice 4:

In [29]:
arr[4]

20

En Python el índice -1 hace referencia a la última posición de la colección, el -2 al penúltimo, etc. 

Así que también podemos utilizar índices negativos en arrays:

In [30]:
arr[-1]

45

Pero no sirven únicamente para consultar, también sirven para modificar valores:

In [31]:
arr[0] = 99

arr

array([99,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### Slicing
La técnica del slicing **nos permite acceder y modificar un rango de valores** de un array.

Se basa en dos índices, uno de inicio y otro de fin separados por dos puntos. Si dejamos los índices vacíos se toman por defecto el principio y el final:

In [32]:
arr[:]

array([99,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Para conseguir un subarray de los 3 primeros elementos haríamos [:3] o [0:3]:

In [33]:
arr[:3]

array([99,  5, 10])

Para modificar un rango del array podemos hacerlo de forma masiva con un valor:

In [34]:
arr[1:-1] = 50

arr

array([99, 50, 50, 50, 50, 50, 50, 50, 50, 45])

### Consideraciones importantes
Los arrays de Numpy tienen una característica muy especial, se encuentran referenciados en la memoria.

¿Qué significa eso? Pues que a la hora de trabajar con subarrays todos los cambios que hagamos se verán reflejados en el array original.

Fijaros...

In [37]:
# Reiniciamos el array a como estaba
arr = np.arange(0, 50, 5)

arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [39]:
# Extraemos una subarray
sub_arr = arr[0:4]

sub_arr

array([ 0,  5, 10, 15])

Por ahora todo bien. Vamos a modificar este subarray:

In [42]:
sub_arr[:] = 50

sub_arr

array([50, 50, 50, 50])

Ahora veamos qué ha ocurrido con el array original:

In [44]:
arr

array([50, 50, 50, 50, 20, 25, 30, 35, 40, 45])

¡Pues que se también se ha actualizado!

Esto ocurre porque numpy hace una gestión óptima de la memoria, y no va a malgastarla creando copias por valor.

Para crear una copia real de un array y no modificar el original, tendremos que utilizar el método copy:

In [46]:
arr = np.arange(0, 50, 5)

cop_arr = arr.copy()

cop_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Modificamos la copia...

In [48]:
cop_arr[:] = 50

cop_arr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

Y el original debería seguir intacto:

In [49]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

## Ejercicios