## Arrays de 3 y más dimensiones

Hasta ahora hemos trabajado los arrays de 1 y 2 dimensiones, así que la pregunta es... ¿Será posible hacer lo mismo con 3 o más dimensiones? Pues sí. ¿Pero cómo se hace?

### Creación básica
De la misma forma que un array de 2 dimensiones, el truco para crear uno de 3 consiste en anidar listas a 3 niveles de profundidad. 

Para entender bien el proceso vamos a recrear los 3 niveles de profundidad paso a paso para un array muy simple de 2x2x2

In [2]:
import numpy as np

# Primer nivel, 2 elementos en ancho
arr_1d = np.array([1, 2])

arr_1d

array([1, 2])

In [3]:
# Segundo nivel, 2 elementos en ancho por 2 de alto, 4 elementos en total
arr_2d = np.array([[1, 2], [3, 4]])

arr_2d

array([[1, 2],
       [3, 4]])

In [5]:
# Tercer nivel, 2 elementos en ancho por 2 de alto por 2 de profundidad, 8 elementos en total
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Con esto tenemos las 3 dimensiones, pero podemos añadir más. 

El concepto es difícil de imaginar, ya que nosotros únicamente percibimos 3 dimensiones, pero si lo entendemos como una ramificación en dónde por cada elemento ahora hay otra lista con dos elementos, entonces no es tan imposible hacernos una idea:

In [6]:
# Cuarto nivel, 2 elementos en ancho por 2 de alto por 2 de profundidad por 2 más, 16 elementos en total
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

### Creación pre-generada de ceros y unos
Evidentemente no siempre vamos a querar crear nuestros arrays de 3 o más dimensiones a mano. También podemos crearlos con las funciones de pre-generación que vimos en la lección 2.

In [44]:
# Array 3d de ceros 2x2x2
arr_3d = np.zeros([2,2,2])

arr_3d

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

In [43]:
# Array 4d de unos 2x2x2x2
arr_4d = np.ones([2,2,2,2])

arr_4d

array([[[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]],


       [[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]]])

### Creación con reshape
Reshape es una función que sirve para reformar las dimensiones y sus tamaños. 

Por ejemplo podemos reformar una matriz de 3x3 a partir de un rango de 9 elementos:

In [78]:
arr_2d = np.arange(9).reshape(3,3)
arr_2d 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Evidentemente tenemos que seguir un patrón lógico, y es que el número de elementos tiene que concordar con el tamaño de las dimensiones multiplicadas.

In [79]:
# Esto no funcionará: 9 != 3x3x3
arr_3d = np.arange(9).reshape(3,3,3)
arr_3d 

ValueError: total size of new array must be unchanged

In [80]:
# Esto sí que funcionará: 27 == 3x3x3
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## Ejercicios