## Arrays transpuestos

Si habéis estudiado el álgebra de matrices seguro que ya sabéis qué es la matriz transpuesta de una matriz.

Si no es así tranquilos, en seguida entenderéis el concepto. Fijaros en este ejemplo:

#### Matriz ${A}$
$\begin{pmatrix}
1 & 2\\
3 & 4\\
5 & 6 
\end{pmatrix}$

#### Matriz ${A^t}$

$\begin{pmatrix}
1 & 3 & 5\\
2 & 4 & 6\\
\end{pmatrix}$

Tal como se puede apreciar una matriz transpuesta es una matriz que refleja a otra, de manera que las columnas se vuelven filas y las filas columnas.

Evidentemente la transpuesta de una matriz transpuesta es equivalente a la original:  ${(A^t)^t}$ = ${A}$

Lo interesante es que con Numpy podemos conseguir el array transpuesto muy fácilmente.

In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Tranpuesto
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# Tranpuesta de la transpuesta
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

Por cierto, la función **swapaxes** sirve precisamente para intercambiar la posición de los dos ejes de un array, así que sirve para lo mismo:

In [23]:
# Intercambiar las filas por las columnas
arr.swapaxes(0,1)
arr.swapaxes(1,0) # Es lo mismo

array([[1, 4],
       [2, 5],
       [3, 6]])

Evidentemente también podemos encontrar el array transpuesto de un array de 3 o más dimensiones:

In [25]:
# Creamos un array 3d
arr_3d = np.arange(8).reshape(2,2,2)
arr_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
# Buscamos el array transpuesto
arr_3d.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

O intercambiar los ejes con **swapaxes**, por ejemplo la primera dimensión por la tercera, que en nuestro caso sería equivalente al array transpuesto:

In [34]:
arr_3d.swapaxes(0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

En cambio no lo sería intercambiar la primera por la segunda:

In [35]:
arr_3d.swapaxes(0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

## Ejercicios