## Funciones universales
En esta lección vamos a ver algunas de las funciones universales de la clase array de Numpy.  Se llaman universales porque sirven para aplicar funciones matemáticas comunes a los elementos del array.

Podemos encontrar **operaciones matemáticas**, **trigonométricas**, **flotantes**, **comparativas** y de cambios de bits. 

[En este enlace a la documentación oficial](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) encontraréis el listado completo con ejemplos de uso. 

Por ahora vamos a practicar algunas de las más comunes.

### Matemáticas

In [67]:
import numpy as np

# Declaramos un array de prueba
arr_1 = np.arange(1,6)
arr_1

array([1, 2, 3, 4, 5])

In [68]:
# Otro array
arr_2 = np.array([-3,7,3,13,0])
arr_2

array([-3,  7,  3, 13,  0])

In [69]:
# Suma
np.add(arr_1, arr_2)

array([-2,  9,  6, 17,  5])

In [70]:
# Resta
np.subtract(arr_2, arr_1)

array([-4,  5,  0,  9, -5])

In [71]:
# Raiz cuadrada
np.sqrt(arr_1)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798])

In [72]:
# Potencia
np.power(arr_1, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [73]:
# Signo
np.sign(arr_1)

array([1, 1, 1, 1, 1])

### Trigonométricas

In [74]:
# Seno
np.sin(arr_1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [75]:
# Tangente
np.tan(arr_1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [76]:
# Grados a radianes
np.deg2rad(arr_1)

array([ 0.01745329,  0.03490659,  0.05235988,  0.06981317,  0.08726646])

### Comparativas

In [77]:
# Máximo
np.maximum(arr_1, arr_2)

array([ 1,  7,  3, 13,  5])

In [78]:
# Igual
np.equal(arr_1, arr_2)

array([False, False,  True, False, False], dtype=bool)

In [94]:
# Mayor
np.greater(arr_1, arr_2)

array([ True, False, False, False,  True], dtype=bool)

### Flotantes

In [83]:
arr_3 = np.array([3.14, 2.57, -6.4, 0.47, 5.5])
arr_3

array([ 3.14,  2.57, -6.4 ,  0.47,  5.5 ])

In [90]:
# Valor absoluto
np.fabs(arr_3)

array([ 3.14,  2.57,  6.4 ,  0.47,  5.5 ])

In [88]:
# Techo (redondeo entero siempre al alza)
np.ceil(arr_3)

array([ 4.,  3., -6.,  1.,  6.])

In [89]:
# Suelo (redondeo entero siempre a la baja)
np.floor(arr_3)

array([ 3.,  2., -7.,  0.,  5.])

## Ejercicios