## Funciones aleatorias
Ya que estamos repasando funciones no podemos olvidar las funciones aleatorias de Numpy, encontradas en el módulo random.

[En este enlace a la documentación oficial](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html) encontraréis el listado completo con ejemplos de uso. 

Tenemos funciones para generar arrays con **datos aleatorios** y **permutaciones**. También hay muchas enfocadas a generar muestras de distribuciones de probabilidadpensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

### Datos aleatorios

In [1]:
import numpy as np

# Número decimal entre 0 y 1
np.random.rand()

0.9538418419856016

In [176]:
# Array 1D de decimales entre 0 y 1
np.random.rand(4)

array([ 0.98037833,  0.68852893,  0.94593868,  0.79645589])

In [177]:
# Array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[ 0.9514949 ,  0.91115546],
       [ 0.07018065,  0.76570926],
       [ 0.96519048,  0.02009274],
       [ 0.65534272,  0.79159674]])

In [188]:
# Array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[ 8.61778202,  6.81368708],
        [ 7.99862719,  3.64448439]],

       [[ 7.11681674,  8.11517456],
        [ 5.29141264,  3.27754127]]])

In [189]:
# Array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[ 5.94066981, -6.10081435],
         [-4.85375846,  4.51694499]],

        [[ 3.1264627 , -8.57035636],
         [ 4.71590752,  8.51147178]]],


       [[[ 9.83840494,  8.51724141],
         [ 0.59540768, -0.44959352]],

        [[-4.82373399,  4.13123614],
         [-4.25213011, -0.60892714]]]])

In [179]:
# Número entero entre 0 y N
np.random.randint(10)

9

In [180]:
# Array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[8, 4],
       [7, 4],
       [0, 0]])

In [181]:
# Array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ 9, -7],
       [ 5,  4],
       [ 7,  7]])

In [7]:
# Array uniforme (con curva gaussiana)
np.random.normal(size=100)

array([  99.58174011,   98.94019668,   99.38469781,   99.81314095,
        100.53315255,  100.66852502,   99.56303652,   99.76540897,
        101.68074673,   99.05441905,  102.76941684,  100.6067768 ,
        102.47589732,   98.24117958,   99.70057972,  101.3281897 ,
         99.60896769,   99.590368  ,   99.34372526,  100.5856358 ,
         99.03727702,  100.99962394,  100.1171753 ,  101.81315307,
        101.05467297,   99.95206384,  101.87587947,   99.24353297,
        100.61992394,   99.80765468,  102.53542462,  100.25564025,
        100.40811632,  100.02837631,   98.26766458,   99.60548698,
        102.09994144,   98.61632723,   99.93566814,  101.5493894 ,
        100.55594049,   98.71575397,   98.02042488,   98.87100594,
         97.2010937 ,  101.14885017,  101.67757319,  100.24826179,
         99.23350491,   99.27491934,  100.35762076,   98.33052381,
         98.45015526,  100.23155581,   99.49096989,   99.99585077,
        100.13632862,  100.69897952,   99.04455444,  101.32800

### Permutaciones

In [182]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
# Desordenar un array (lo cambia)
np.random.shuffle(arr)
arr

array([3, 0, 6, 4, 7, 5, 1, 9, 8, 2])

In [184]:
# Generar secuencia permutada a partir de un array (no lo cambia)
np.random.permutation(arr)

array([9, 4, 0, 3, 6, 1, 7, 8, 5, 2])

In [185]:
arr

array([3, 0, 6, 4, 7, 5, 1, 9, 8, 2])

## Ejercicios