## Filtrado de Arrays
En esta lección vamos a repasar algunas funciones para filtrar nuestros arrays. 

Si queréis más información sobre las funciones disponibles no olvidéis pasaros por [la documentación oficial en este enlace](https://docs.scipy.org/doc/numpy-1.12.0/reference/index.html).

### Filtro unique
Devuelve un array de una dimensión borrando todos los elementos duplicados.

In [172]:
np.unique(arr)

array([0, 1, 3])

In [170]:
arr = np.random.randint(0, 4, 10)
arr

array([1, 3, 1, 0, 0, 1, 1, 3, 3, 1])

### Filtro in1d
Devuelve un array de una dimensión indicando si los elementos de una lista se encuentran en un array.

In [170]:
arr = np.random.randint(0, 4, 10)
arr

array([1, 3, 1, 0, 0, 1, 1, 3, 3, 1])

In [175]:
np.in1d([-1, 3, 2], arr)

array([False,  True,  True], dtype=bool)

### Filtro where
Esta función sirve para generar un array filtrado a partir de una condición y un valor por defecto.

In [52]:
import numpy as np

# Generamos un array de aleatorios
arr_1 = np.random.uniform(-5, 5, size=[3,2])
arr_1

array([[-0.98717086,  1.83169932],
       [-2.60592487,  2.81209934],
       [ 2.00392765,  1.44204738]])

In [53]:
# Creamos un filtro que establece los negativos a 0
arr_2 = np.where(arr_1<0, 0, arr_1)
arr_2

array([[ 0.        ,  1.83169932],
       [ 0.        ,  2.81209934],
       [ 2.00392765,  1.44204738]])

In [54]:
# Añadimos otro filtro que establece los positivos a 1
arr_2 = np.where(arr_2>0, True, arr_2)
arr_2

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  1.]])

In [62]:
# Podemos crear nuestros propios arrays de condiciones
arr_3 = np.array([1, -2, 3, -4, 5])
arr_4 = np.array([-1, 2, -3, 4, -5])

arr_cond = np.array([True, False, True, False, True])

np.where(arr_cond, arr_3, arr_4)

array([1, 2, 3, 4, 5])

### Filtros booleanos

In [90]:
# Comprobar si todos los elementos de un array son True
arr_bool = np.array([True,True,True,False])
arr_bool.all()

False

In [92]:
# Comprobar al menos un elemento del array es True
arr_bool = np.array([True,True,True,False])
arr_bool.any()

True

In [118]:
# También aplican a un eje en particular
arr_bool = np.array([[True,True],[False,True],[True,True]])
arr_bool

array([[ True,  True],
       [False,  True],
       [ True,  True]], dtype=bool)

In [120]:
# Columas verdaderas
arr_bool.all(0)

array([False,  True], dtype=bool)

In [122]:
# Filas verdaderas
arr_bool.all(1)

array([ True, False,  True], dtype=bool)

## Ejercicios