## Métodos internos
En esta lección vamos a repasar algunos métodos matemáticos y de ordenación que incluye la clase array de Numpy.

Para más información tenéis como siempre [la documentación oficial en este enlace](https://docs.scipy.org/doc/numpy-1.12.0/reference/index.html).

### Métodos matemáticos

In [79]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
# Sumatorio
arr.sum()

21

In [83]:
# Media
arr.mean()

3.5

In [86]:
# Desviación estándard
arr.std()

1.707825127659933

In [87]:
# Varianza
arr.var()

2.9166666666666665

### Métodos de ordenación

In [163]:
# Ordenar un array
arr = np.random.randint(-10,10,[3,3])
arr

array([[ 0, -8,  1],
       [-1, -7, -1],
       [-4, -4, -6]])

In [164]:
# Ordenar elementos automáticamente (se ordenan en horizontal y se actualiza el array)
arr.sort()
arr

array([[-8,  0,  1],
       [-7, -1, -1],
       [-6, -4, -4]])

In [ ]:
# Ordenar verticalmente utilizando el eje 0
arr.sort(0)
arr

## Ejercicios